name:
description:
date:
cite:
  text:
  doi:
authors:
documentation:
covers:
test_input:
test_output:
tags:
license:
format_version:
language:
framework:
source:
model:
  source:
  sha256:
weights:
  - id:
    name:
    description:
    source:
    sha256:
config:
# custom config for DeepImageJ, see https://github.com/bioimage-io/configuration/issues/23
  deepimagej:
    model_keys:
      # In principle the tag "SERVING" is used in almost every tf model
      model_tag: tf.saved_model.tag_constants.SERVING
      # Signature definition to call the model. Again "SERVING" is the most general
      signature_definition: tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
    test_information:  
      input_size:
      output_size:
      device:
      memory_peak:
      runtime:
      pixel_size:
inputs:
- name:
  axes:
  data_type:
  data_range:
  shape:
    exact:
outputs:
- name:
  axes:
  data_type:
  data_range:
  halo:
  shape:
    reference_input:
    scale:
    offset:
prediction:
  weights:
  preprocess:
    spec: deepimagej.runMacro::preprocessing
    kwargs: {preprocessing.txt}
  postprocess:
    spec: deepimagej.runMacro::preprocessing
    kwargs: {postprocessing.txt}
  dependencies: deepimagej
